---
title: "Booze Models"
format: html
editor: visual
jupyter: python3
---

# Set Up
```{r}
library(tidyverse)
booze <- read.csv(here::here("grouped_data_booze.csv"))
```

# Booze Models

```{r}
booze <- booze |>
  mutate(
    company = as.factor(company),
    date = as.Date(paste0(date, "-01")),
    year = as.numeric(format(date, "%Y")),
    month = as.numeric(format(date, "%m"))
  )

booze_large_chains <- booze |>
  filter(num_stores >= 5)

DEAD <- DEAD |>
  mutate(
    county = as.factor(county),
    alcohol_type = as.factor(alcohol_type),
    year = date
  )

#one-hot encoding
county_dummies <- model.matrix(~ county, data = DEAD)
county_dummies <- county_dummies[, -1]
alcohol_dummies <- model.matrix(~ alcohol_type, data = DEAD)
alcohol_dummies <- alcohol_dummies[, -1]
DEAD <- cbind(DEAD, county_dummies, alcohol_dummies)
```


# Custom Functions:
```{r}
cross_validation_split <- function(dataset, k) {
  set.seed(40313)
  n <- nrow(dataset)
  groups <- 1:k
  assignments <- rep(c(groups), length.out=n)
  assignments <- sample(assignments)
  dataset[["cv_group"]] <- assignments
  return(dataset)
}
```

```{r}
fit_cv <- function(dataset, predictor_cols, response, k=5) {
  df_cv <- cross_validation_split(dataset, k)
  cv_groups <- df_cv$cv_group
  metrics <- c()
  for(i in 1:k) {
    test_set <- df_cv[df_cv$cv_group == i, ]
    train_set <-  df_cv[df_cv$cv_group != i, ]
    X_train <- as.matrix(train_set[, predictor_cols])
    X_train <- cbind(intercept = 1, X_train)
    y_train <- as.matrix(train_set[, response])
    X_test <- as.matrix(test_set[, predictor_cols])
    X_test <- cbind(intercept = 1, X_test)
    y_test <- as.vector(test_set[, response])
    model <- fit_linear_model(X_train, y_train)
    test.predictions <- predict_linear(model, X_test)
    r2 <- calculate_r2(y_test, test.predictions)
    metrics <- c(metrics, r2)
  }
  cv_r2 <- sum(metrics)/k
  return(cv_r2)
}
```

```{r}
fit_linear_model <- function(X, y) {
  XtX <- t(X) %*% X
  XtX_inv <- solve(XtX)
  Xty <- t(X) %*% y
  coefficients <- XtX_inv %*% Xty
  return(list(
    coefficients = as.vector(coefficients),
    feature_names = colnames(X)
  ))
}

#predictions
predict_linear <- function(model, X_new) {
  predictions <- X_new %*% model$coefficients
  return(as.vector(predictions))
}

#R^2: 1 - (SS_res / SS_tot)
calculate_r2 <- function(y_true, y_pred) {
  ss_res <- sum((y_true - y_pred)^2)
  ss_tot <- sum((y_true - mean(y_true))^2)
  r2 <- 1 - (ss_res / ss_tot)
  return(r2)
}
```

# Booze Models
```{r}
predictor_cols <- c("num_stores", "year", "month")
response <- "sum_sale_dollars"
results <- fit_cv(booze, predictor_cols, response, k = 10)
print(paste("CV R^2:", round(results, 4)))
```
```{r}
predictor_cols <- c("num_stores", "year", "month")
response <- "sum_sale_dollars"
results <- fit_cv(booze_large_chains, predictor_cols, response, k = 10)
print(paste("CV R^2:", round(results, 4)))
```
```{r}
X <- as.matrix(booze[, predictor_cols])
X <- cbind(intercept = 1, X)
y <- as.matrix(booze[, response])
    
model <- fit_linear_model(X, y)
print(model)
```





Using Built in Functions

```{r}
library(tidymodels)
booze <- booze |>
  #separate(date, into = c("year", "month"), sep = "-") |>
  mutate(
    #across(c(year, month), as.factor),
           company = as.factor(company))

booze_large_chains <- booze |>
  filter(num_stores >= 5)
```

```{r}
lin_reg <- linear_reg() |>
  set_mode("regression") |>
  set_engine("lm")

#USE THIS SEED FOR CONSISTENCY
set.seed(40313)
booze_cv <- vfold_cv(booze, v = 10)
booze_large_cv <- vfold_cv(booze, v=10)
```

Predict sum Sale Dollars from num stores for companys with large amount of stores

```{r}
booze_rec1 <- recipe(sum_sale_dollars ~ num_stores + date,
                        data=booze) |>
    step_mutate(
    year = substr(date, 1, 4),
    month = substr(date, 6, 7)
  ) |>
  step_mutate(
    year = factor(year),
    month = factor(month)
  ) |>
  step_dummy(all_nominal_predictors()) |>
  step_normalize(all_numeric_predictors())

booze_cv1 <- lin_reg |>
  fit_resamples(booze_rec1,
                resamples = booze_cv)

booze_cv1 |> collect_metrics()
```

```{r}
booze_rec2 <- recipe(sum_sale_dollars ~ date + num_stores,
                        data=booze_large_chains) |>
    step_mutate(
    year = substr(date, 1, 4),
    month = substr(date, 6, 7)
  ) |>
  step_mutate(
    year = factor(year),
    month = factor(month)
  ) |>
  step_dummy(all_nominal_predictors()) |>
  step_normalize(all_numeric_predictors())

booze_cv2 <- lin_reg |>
  fit_resamples(booze_rec2,
                resamples = booze_large_cv)

booze_cv2 |> collect_metrics()
```

